# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'QRCode_tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for QRCode_tutorial
  pod 'QRCodeReader.swift', '~> 10.1.0'

end
